// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

import (
	"time"
)

const TableNameLlmModel = "llm_model"

// LlmModel 模型信息
type LlmModel struct {
	ModelKey      string    `gorm:"column:model_key;primaryKey;comment:模型标识" json:"model_key"`                            // 模型标识
	ModelName     string    `gorm:"column:model_name;not null;comment:模型名称" json:"model_name"`                            // 模型名称
	API           string    `gorm:"column:api;not null;comment:模型api名称" json:"api"`                                       // 模型api名称
	BindImBotName string    `gorm:"column:bind_im_bot_name;not null;comment:模型绑定的IM bot名称" json:"bind_im_bot_name"`       // 模型绑定的IM bot名称
	BindImBotID   string    `gorm:"column:bind_im_bot_id;not null;default:0;comment:模型绑定的IM botId" json:"bind_im_bot_id"` // 模型绑定的IM botId
	IsDelete      int32     `gorm:"column:is_delete;not null;comment:是否删除 0-否 1-是" json:"is_delete"`                      // 是否删除 0-否 1-是
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`  // 创建时间
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:修改时间" json:"updated_at"`  // 修改时间
}

// TableName LlmModel's table name
func (*LlmModel) TableName() string {
	return TableNameLlmModel
}
